apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init-multiple-dbs.sql: |
    CREATE DATABASE shipment_db;
    CREATE DATABASE warehouse_db;
    CREATE DATABASE routing_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init-multiple-dbs.sql
          subPath: init-multiple-dbs.sql
      volumes:
      - name: init-script
        configMap:
          name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432